// pages\index.js
// Created by: Nirav, Pratham, Parita, Jay
// Last Updated by: Pratham on August 03
import Head from 'next/head'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>HireQuiz.com | Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="homePage" className="row">
          <div className="col-md-7">
            <br/>
            <br/>
            <h1><b>GET HIRED NOW!</b></h1>
            <h3>Let's get started in landing your first job.</h3>
            <br />
            <h4>Click the below link to view Job Postings</h4>
            <a href="/login" className="btn btn-primary">
              <b>View Job Postings</b>
            </a>
            
            <a href="/userform" className="btn btn-primary">
            <b>Form</b>
            </a>
          </div>
          <div className="col-md-4">
            <img src="https://www.commbox.io/wp-content/uploads/2019/10/32-1.jpg" alt="HireQuiz.ca" height="400" width="500"></img>
          </div>
        </div>
      </main>
    </>
  )
}
